name: Master

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Clean install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:jest
